services:
    web:
      image: nginx
      volumes: 
        - ./Website/src/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./Website/src:/var/www/html
      network_mode: "host"
    camera:
      devices: 
        - "/dev/video0:/dev/video1"
        - "/dev/video0:/dev/video2"
      build: 
        context: ./Camera
        dockerfile: Dockerfile
      network_mode: "host"
    server:
      ports: 
        - "5000:5000"
      build: 
        context: ./Server
        dockerfile: Dockerfile